ALTER TABLE PermissionToAccessADepartment DROP CONSTRAINT FKPermission781867;
ALTER TABLE SetOfPermissionIncludeRoleInfo DROP CONSTRAINT FKSetOfPermi200389;
ALTER TABLE RoleInfoIncludePermission DROP CONSTRAINT FKRoleInfoIn46240;
ALTER TABLE SetOfPermissionIncludePermission DROP CONSTRAINT FKSetOfPermi203895;
ALTER TABLE SetOfPermissionIncludePermission DROP CONSTRAINT FKSetOfPermi863100;
ALTER TABLE PersonBelongToDepartment DROP CONSTRAINT FKPersonBelo859937;
ALTER TABLE PersonBelongToDepartment DROP CONSTRAINT FKPersonBelo83296;
ALTER TABLE Card DROP CONSTRAINT PersonOfCard;
ALTER TABLE Department DROP CONSTRAINT ParentDeptId;
ALTER TABLE FingerPrint DROP CONSTRAINT PersonOfFingerPrint;
ALTER TABLE SetOfPermissions DROP CONSTRAINT PersonOfSetOfPermission;
ALTER TABLE PermissionToAccessADepartment DROP CONSTRAINT DepartmentOfPermission;
ALTER TABLE PassEvent DROP CONSTRAINT SourceOfPassEvent;
ALTER TABLE PassEvent DROP CONSTRAINT PersonOfPassEvent;
ALTER TABLE NotificationChannel DROP CONSTRAINT PersonOfNotificationChannel;
ALTER TABLE SetOfPermissionIncludeRoleInfo DROP CONSTRAINT FKSetOfPermi881879;
ALTER TABLE RoleInfoIncludePermission DROP CONSTRAINT FKRoleInfoIn376823;
ALTER TABLE PassEvent DROP CONSTRAINT TypeOfPassEvent;
ALTER TABLE Notification DROP CONSTRAINT StatusOfNotification;
ALTER TABLE Notification DROP CONSTRAINT PassEventForNotification;
ALTER TABLE UserInfo DROP CONSTRAINT PersonOfUserInfo;
ALTER TABLE Permission DROP CONSTRAINT TypeOfPermission;
ALTER TABLE Notification DROP CONSTRAINT ChannelOfNotification;
ALTER TABLE NotificationChannel DROP CONSTRAINT TypeOfNotificationChannel;
ALTER TABLE PermissionToAccessAPerson DROP CONSTRAINT FKPermission795882;
ALTER TABLE PermissionToAccessAPerson DROP CONSTRAINT PersonOfPermission;
DROP TABLE SetOfPermissionIncludeRoleInfo;
DROP TABLE RoleInfoIncludePermission;
DROP TABLE SetOfPermissionIncludePermission;
DROP TABLE PersonBelongToDepartment;
DROP TABLE Card;
DROP TABLE Department;
DROP TABLE FingerPrint;
DROP TABLE NotificationChannel;
DROP TABLE NotificationChannelType;
DROP TABLE SetOfPermissions;
DROP TABLE RoleInfo;
DROP TABLE Permission;
DROP TABLE PermissionType;
DROP TABLE PermissionToAccessAPerson;
DROP TABLE PermissionToAccessADepartment;
DROP TABLE PassEvent;
DROP TABLE PassType;
DROP TABLE PassSource;
DROP TABLE UserInfo;
DROP TABLE Notification;
DROP TABLE NotificationStatus;
DROP TABLE Person;
